LOCO 5
STOD 10

LOCO 0
STOD 11

CALL add_proc
JUMP end

add_proc: LOCO 1
          PUSH
          STOD 1
          LOCO 2
          PUSH
          LOCO 3
          PUSH
          LOCO 4
          PUSH
          LOCO 5
          PUSH

          loop: POP
            ADDD 11
            STOD 11
            LODD 10
            SUBD 1
            STOD 10
            JNZE loop
          RETN
end: LODD 11